spring:
  application:
    name: store

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refreshExpiration: ${JWT_REFRESH_EXPIRATION}

  stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}

  profiles:
    active: dev

